name: Docker Build & Publish to github packages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Set up QEMU 🐳
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: GitHub Actions Cache Docker layers 📦
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', 'path/to/dependencies/**') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Registry 🚢
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: adrianhuszka
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/12szf2/pollak-idopontfoglalo/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  triggerUpdate:
    name: Trigger Update 🔄
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Call Webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
